plugins {
    id "com.android.application"
}

android {
    namespace "com.jadde.alarmemedicamentos"
    compileSdk 35

    defaultConfig {
        applicationId "com.jadde.alarmemedicamentos"
        minSdk 26
        targetSdk 28
        versionCode 1
        versionName "1.0.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }
}
